# Generated by Django 3.0.8 on 2020-07-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='owner',
            new_name='author',
        ),
    ]
