# Generated by Django 3.0.8 on 2020-07-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200712_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='author',
            new_name='user',
        ),
    ]
